ARG VERSION=v3.2.1

FROM prom/prometheus:${VERSION}

# Create directory for certificates
RUN mkdir -p /etc/prometheus/certs

# Copy the configuration file to the container
COPY prom.yml /etc/prometheus/prom.yml

# Command to run Prometheus
CMD ["--config.file=/etc/prometheus/prom.yml", "--storage.tsdb.path=/prometheus"]