global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "app-metrics"
    static_configs:
      - targets: ["caddy-production-669f.up.railway.app"]
    metrics_path: "/api/metrics"
    scrape_interval: 15s