global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "app-metrics"
    static_configs:
      - targets: ["web.railway.internal"]
    metrics_path: "/metrics"
    scrape_interval: 30m
    bearer_token: ${METRICS_TOKEN:-metrics-token}